name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        id: demo_1
        run: exit 1
      - name: I will be skipped
        if: ${{ !failure() }}
        run: echo "I will print if previous steps succeed."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "I will print if any previous step fails"
      - name: I Will execute
        if: ${{ !cancelled() }}
        run: echo "I will laways print, except wwhen the workflow is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "I will always print"
      